#pragma config(Motor,  port1,           TM_Right,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           Front_Left,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           Back_Left,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           Back_Right,    tmotorVex393, openLoop)
#pragma config(Motor,  port5,           Front_Right,   tmotorVex393, openLoop)
#pragma config(Motor,  port6,           M_TopLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port7,           M_BottomLeft,  tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           M_TopRight,    tmotorVex393, openLoop)
#pragma config(Motor,  port9,           M_BottomRight, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          TM_Left,       tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Note: Alex is dumb. You cannot put comments before the Declaration of Motor Independence >:|    ^^


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{
	motor[port1] = -127;
	motor[port10] = -127;
	wait1Msec(300);
	motor[port1] = 0;
	motor[port10] = 0;
	motor[port2] = -127;
	motor[port3] = -127;
	motor[port4] = -127;
	motor[port5] = -127;
	wait1Msec(100);
	motor[port2] = 0;
	motor[port3] = 0;
	motor[port4] = 0;
	motor[port5] = 0;
}

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

	if (vexRT[Ch3] > 25 || vexRT[Ch3] < -25)
	{
		motor[Back_Left] = vexRT[Ch3];
		motor[Front_Left] = vexRT[Ch3];
	}else{
		motor[Back_Left] = 0;
		motor[Front_Left] = 0;
	}
	if (vexRT[Ch2] > 25 || vexRT[Ch2] < -25)
	{
		motor[Back_Right] = vexRT[Ch2];
		motor[Front_Right] = vexRT[Ch2];
	}else{
		motor[Back_Right] = 0;
		motor[Front_Right] = 0;
	}

		motor[M_BottomLeft] = vexRT[Ch3Xmtr2];
		motor[M_TopLeft] = vexRT[Ch3Xmtr2];
		motor[M_BottomRight] = vexRT[Ch3Xmtr2];
		motor[M_TopRight] = vexRT[Ch3Xmtr2];

		motor[TM_Right] = vexRT[Ch2Xmtr2];
		motor[TM_Left] = vexRT[Ch2Xmtr2];
	}
}
